version: '3.9'

services:
  web:
      build : .
      restart : "always"
      ports :
        - "4000:4000"
      depends_on : 
        - db
      links:
        - "db:warehouse"


  db:
      image : "postgres:14.5-alpine"
      restart : "always"
      environment:
        POSTGRES_USER : 'abhishek_raj'
        POSTGRES_PASSWORD : 'iamawesome'
      volumes :
        - db_data:/var/lib/postgresql/data
volumes:
  db_data:
